### ISSUE TITLE
Test failure/crash: Seeing "slave gw" crashes/messages in Sauce Labs with Firefox 42 on Windows 10 when test_upcoming_events_are_displayed runs

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#451] opened 2015-11-12 22:49 UTC
Sorry, this might not really be mcom-tests-specific, but seems to show up in this suite most often, as least.

@davehunt  and I discussed this, and IIRC, we suspect there's a chance it's an actual Selenium issue, but filing to try to get a handle on it.

See https://webqa-ci.mozilla.com/job/bedrock.dev.win10.firefox/85/HTML_Report/

tests/functional/test_home.py::test_upcoming_events_are_displayed fails with Slave 'gw10' crashed while running 'tests/functional/test_home.py::test_upcoming_events_are_displayed'

Sauce Labs job: https://saucelabs.com/tests/2ebb8ffb50644d1b9f936200194fafc5 is the corresponding video

**Comment by alexgibson** [comment] 2015-11-12 22:54
We've been seeing this same error message on the mcom tests repo regularly too, on various seemingly random tests, e.g.

https://webqa-ci.mozilla.com/job/mozilla.org.prod.win7.chrome.saucelabs/848/

**Comment by stephendonner** [comment] 2015-11-12 23:18
Yes, thanks, Alex - I had pasted the wrong links.  Long day :-(

**Comment by davehunt** [comment] 2015-11-13 09:05
Both of these show stack traces that indicate an error was returned when attempting to close the browser. It could be that pytest-xdist (this is the plugin that manages the slave processes) doesn’t handle such exceptions well and crashed the process. Ideally we need to find the cause of the failure and fix/prevent it.

Sauce Labs sees this as a timeout, with no commands after 90 seconds: https://saucelabs.com/beta/tests/1fe71583d42b48d2852d1bc257741f78/commands

Looking at the logs it appears that Sauce never received the command to close the browser. It’s possible that the exception is therefore caused by the session not existing at that time (due to the timeout). I’ve seen this a few times recently, even where Sauce appears to not receive the command to get the text of an element immediately after successfully locating the element. It could be that our network is dropping these packets somehow or Sauce is somehow not processing them correctly.

One issues that is also affecting us is that we’re using the 2.48 Python client for Selenium, but the 2.47 server. The error handling was changed in this time, and explains why we see the "No JSON object could be decoded” message instead of the actual error message. I’ve been working on getting all of our suites ready for 2.48 but due to other changes related to element click interactions, it’s taken me some time.

Immediate (temporary) suggestions:
* Pin our suites to the Selenium 2.47 python client bindings (only resolves the incorrect traceback)
* Enable rerun failures so that we automatically rerun and 'pave over’ these failures

Longer term suggestions:
* Upgrade to Selenium 2.48 server
* Add tolerance to pytest-selenium for exceptions on debug gathering and closing the browser (could mask real issues), there's also an issue open already for this: https://github.com/davehunt/pytest-selenium/issues/40
* Investigate the possibility of dropped network packets, perhaps in collaboration with Sauce Labs in case the issue is on their side

**Comment by stephendonner** [comment] 2015-11-19 01:18
In case this helps, it also happened in https://webqa-ci.mozilla.com/job/mozillians.stage.saucelabs/637/HTML_Report/ - Slave 'gw8' crashed while running 'tests/test_search.py::TestSearch::()::test_search_for_not_existing_mozillian_when_logged_in'

**Comment by davehunt** [comment] 2015-11-19 09:19
Interesting... it looks like we're using the proxy between Jenkins and Selenium Grid, which I don't think we should be doing. That should not be a problem though, and the proxy will be needed for our Sauce Labs jobs. I wonder if there's something wrong with the proxy dropping packets and causing our tests to not receive responses from the Selenium server?

**Comment by davehunt** [comment] 2015-11-19 09:23
Sorry, my mistake, that *is* a Sauce Labs job. Any idea who we can ask about potential issues with the proxy?

**Comment by davehunt** [comment] 2015-11-19 09:29
Here's the information from the console log at **13:57:25** that's of particular interest:

> \<h1>ERROR\</h1>
\<h2>The requested URL could not be retrieved\</h2>
\<p>The following error was encountered while trying to retrieve the URL: <a href="http://162.222.75.179/wd/hub/session/11804d03131d49e98927bcac6e8ebf7f/url">http://162.222.75.179/wd/hub/session/11804d03131d49e98927bcac6e8ebf7f/url</a>\</p>
\<p>\<b>Zero Sized Reply\</b>\</p>
\<p>Squid did not receive any data for this request.\</p>

**Comment by davehunt** [comment] 2016-02-26 09:29
We're still investigating our infrastructure regarding these proxy timeouts, all other issues mentioned here have (I believe) been resolved. I'm closing this as the remaining issue is being tracked [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1238977).

**Closed by davehunt** 2016-02-26 09:29 UTC
Labels: difficulty intermediate, priority high, Test Failure
